name: preview.graphql-debugger.com

on:
  push:
    branches:
      - feat/next-docs

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          timeout: 60s
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ./preview/graphql-debugger
            git reset --hard
            git pull origin feat/next-docs
            pnpm i
            pnpm build
            cd ./docs/
            pm2 restart preview
