name: Release

on: 
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-project
      - run: cd ./packages/graphql-debugger && chmod +x ./build/index.js
      - run: START_PATH="." node ./packages/utils/build/bump-versions.js
        env:
          VERSION: ${{github.ref_name}}
      - run: pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
      - run: pnpm publish -r --filter '!@graphql-debugger/landing-page-app' --filter '!@graphql-debugger/landing-page-server' --no-git-checks
  #TODO
  #Since we're already building the image in the quality testing, we should try to reuse that.
  #
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_LOGIN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with: #TODO This needs to be variables
          images: mediocredevops/graphql-debugger

      #TODO
      #Re-use artifacts from existing jobs
      #https://docs.github.com/actions/using-workflows/storing-workflow-data-as-artifacts
      #
      #Use tags https://github.com/docker/metadata-action
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

