name: Release

on:
  push:
    tags:
      - '*'

# on:
#   push:
#     branches:
#       - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: npm i -g turbo@1.10.7
      - run: pnpm install
      - run: pnpm build
      - run: cd ./packages/graphql-debugger && chmod +x ./build/index.js
      - run: node ./utils/bump-versions.js
        env:
          VERSION: ${{github.ref_name}}
      - run: pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
      - run: pnpm publish -r --no-git-checks
