name: Setup Project

on:
  workflow_call:

env:
  PNPM_VERSION: 8.0.0
  NODE_VERSION: 18
  TURBO_VERSION: 1.10.7

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Install Turbo
        run: npm i -g turbo@${{ env.TURBO_VERSION }}
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm build
