name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2
        with:
          version: 8.0.0
      - run: npm i -g turbo@1.10.7
      - run: pnpm install
      - run: pnpm build --force
      - run: pnpm test
