name: Test

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8.0.0
      - run: npm i -g turbo@1.10.7
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
